# Generated by Django 2.2.3 on 2019-07-29 17:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('가게명', models.CharField(max_length=200)),
                ('주소', models.CharField(max_length=400)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('작성자', models.CharField(max_length=200)),
                ('내용', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_comment', models.BooleanField(default=False)),
                ('평점', models.FloatField(choices=[(5, '5점'), (4, '4점'), (3, '3점'), (2, '2점'), (1, '1점')], default=5)),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='com', to='blog.Portfolio')),
            ],
        ),
    ]
